### ISSUE TITLE
Release Plan for `v11.0.x`

### ISSUE THREAD

**Issue by Klaim** [Klaim/fmt-build2#7]
For this new version of `fmt` I would like to spend some time to have the major lacks of this packaging fixed before release+publishing.

Plan:
- [x] Switch to the multi-package organisation #6 
- [x] Test package from upstream (and maybe examples if we find the time) #1 
- [x] Fix and complete the C++ modules support #5 

If you have some other improvements suggestions, feel free to add comments.
